var annotated =
[
    [ "AboutJPanel", "class_about_j_panel.html", "class_about_j_panel" ],
    [ "AreaChart", "class_area_chart.html", "class_area_chart" ],
    [ "BobViz", "class_bob_viz.html", "class_bob_viz" ],
    [ "BubbleChart", "class_bubble_chart.html", "class_bubble_chart" ],
    [ "Chart", "interface_chart.html", "interface_chart" ],
    [ "Colour", "class_colour.html", "class_colour" ],
    [ "ColourMap", "class_colour_map.html", "class_colour_map" ],
    [ "ColumnChart", "class_column_chart.html", "class_column_chart" ],
    [ "DataAttribute", "class_data_attribute.html", "class_data_attribute" ],
    [ "Dataset", "class_dataset.html", "class_dataset" ],
    [ "Error", "class_error.html", "class_error" ],
    [ "Graph", "interface_graph.html", "interface_graph" ],
    [ "GroupPDM2application", "class_group_p_d_m2application.html", null ],
    [ "ImportJPanel", "class_import_j_panel.html", "class_import_j_panel" ],
    [ "InformationJPanel", "class_information_j_panel.html", "class_information_j_panel" ],
    [ "LineChart", "class_line_chart.html", "class_line_chart" ],
    [ "MoreSettingJPanel", "class_more_setting_j_panel.html", "class_more_setting_j_panel" ],
    [ "PieChart", "class_pie_chart.html", "class_pie_chart" ],
    [ "PolarChart", "class_polar_chart.html", "class_polar_chart" ],
    [ "ScatterPlotGraph", "class_scatter_plot_graph.html", "class_scatter_plot_graph" ],
    [ "SelectionVizJPanel", "class_selection_viz_j_panel.html", "class_selection_viz_j_panel" ],
    [ "SettingJPanel", "class_setting_j_panel.html", "class_setting_j_panel" ],
    [ "Slideshow", "class_slideshow.html", "class_slideshow" ],
    [ "StatusJPanel", "class_status_j_panel.html", "class_status_j_panel" ],
    [ "Table", "class_table.html", "class_table" ],
    [ "Visualisation", "class_visualisation.html", "class_visualisation" ],
    [ "VizTypeJPanel", "class_viz_type_j_panel.html", "class_viz_type_j_panel" ]
];